name: Build and Test Cybersecurity Chatbot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up .NET Framework
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.8' # Targeting .NET Framework 4.8 (or use 4.7.2 if preferred)

    # Restore NuGet packages
    - name: Restore dependencies
      run: nuget restore St10443034ChatbotP3.sln

    # Build the solution
    - name: Build solution
      run: msbuild St10443034ChatbotP3.sln /p:Configuration=Release /p:Platform="Any CPU"

    # Placeholder for unit tests
    # Note: Add a test project (e.g., using MSTest) for CyberSecurityChatbot.cs
    - name: Run unit tests
      run: |
        # If a test project is added, use MSTest or another test runner
        # Example: dotnet test St10443034ChatbotP3.Tests/St10443034ChatbotP3.Tests.csproj
        echo "No unit tests configured. Add a test project to enable testing."
      continue-on-error: true # Allow workflow to continue if tests are not yet implemented

    # Optional: Archive build artifacts
    - name: Archive build output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: St10443034ChatbotP3/bin/Release/
